<?php
/**
 * Created by PhpStorm.
 * User: pengjiang
 * Date: 2019/5/13
 * Time: 15:34
 */

namespace api\common\controller;

use service\User;

class ApiUserController extends ApiController
{
    protected $uid = 0;

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->uid = User::instance()->getUid();

        if (empty($this->uid)) {
            $this->error(lang('token_expired'),'',[],403);
        }
    }
}